[functions.autentique-webhook]
verify_jwt = false

[functions.asaas-webhook]
verify_jwt = false

[functions.asaas-generate-monthly]
verify_jwt = false

[functions.asaas-create-charge]
verify_jwt = true

[functions.create-google-meet]
verify_jwt = true

[functions.transfer-conversation]
verify_jwt = true
